/*****************************************************************************
* Copyright (C) 2010
* All rights reserved.
* 所属组件 : ME
* 模块名称 : MEXAxTISxGRAT
* 文件名称 : MEXAxTISxGRAT_tc.h
* 概要描述 :
*	ME组件MEXAxTISxGRAT数据结构定义
* 历史记录 :
* 版本    日期    作者    内容
*****************************************************************************/
#ifndef _MEXAxTISxGRAT_TC_H_
#define _MEXAxTISxGRAT_TC_H_

/*------------------------------- Includes -------------------------------*/



/*-------------------------------- Defines -------------------------------*/
#define MEXAxTISxGRAT_MIN_TIS_SENSOR_GRATING_ID 	 0x0 
#define MEXAxTISxGRAT_MAX_TIS_SENSOR_GRATING_ID 	 0x1B 
#define MEXAxTISxGRAT_MAX_NR_TIS_SENSOR_GRATING_IDS 	 0x1C 
#define MEXAxTISxGRAT_MIN_TIS_MARK_GRATING_ID 	 0x0 
#define MEXAxTISxGRAT_MAX_TIS_MARK_GRATING_ID 	 0x12 
#define MEXAxTISxGRAT_MAX_NR_TIS_MARK_GRATINGS 	 0x13 



/*-------------------------- Enums and Structs ---------------------------*/

typedef enum
{
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA_A0 = 0,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA_A45 = 1,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA_A90 = 2,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA_A135 = 3,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA1_A0 = 4,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA1_A45 = 5,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA1_A90 = 6,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA1_A135 = 7,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA2_A0 = 8,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA2_A45 = 9,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA2_A90 = 10,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TA2_A135 = 11,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TR = 12,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TRA1 = 13,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TRA2 = 14,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TRP = 15,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TXH = 16,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TXP = 17,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TXV = 18,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TYH = 19,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TYP = 20,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TYV = 21,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TCXY = 22,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TCXYZ = 23,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TCXYP = 24,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_TCXYZP = 25,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_T45P = 26,
    MEXAxTISxGRAT_TIS_SENSOR_GRATING_ID_T135P = 27,
} MEXAxTISxGRAT_TIS_sensor_grating_id;

typedef enum
{
    MEXAxTISxGRAT_TIS_MARK_GRATING_XH = 0,
    MEXAxTISxGRAT_TIS_MARK_GRATING_XV = 1,
    MEXAxTISxGRAT_TIS_MARK_GRATING_YH = 2,
    MEXAxTISxGRAT_TIS_MARK_GRATING_YV = 3,
    MEXAxTISxGRAT_TIS_MARK_GRATING_R = 4,
    MEXAxTISxGRAT_TIS_MARK_GRATING_A0 = 5,
    MEXAxTISxGRAT_TIS_MARK_GRATING_A45 = 6,
    MEXAxTISxGRAT_TIS_MARK_GRATING_A90 = 7,
    MEXAxTISxGRAT_TIS_MARK_GRATING_A135 = 8,
    MEXAxTISxGRAT_TIS_MARK_GRATING_RA0 = 9,
    MEXAxTISxGRAT_TIS_MARK_GRATING_RA45 = 10,
    MEXAxTISxGRAT_TIS_MARK_GRATING_RA90 = 11,
    MEXAxTISxGRAT_TIS_MARK_GRATING_RA135 = 12,
    MEXAxTISxGRAT_TIS_MARK_GRATING_CXY = 13,
    MEXAxTISxGRAT_TIS_MARK_GRATING_CXYZ = 14,
    MEXAxTISxGRAT_TIS_MARK_GRATING_45 = 15,
    MEXAxTISxGRAT_TIS_MARK_GRATING_135 = 16,
    MEXAxTISxGRAT_TIS_MARK_GRATING_CLS_X = 17,
    MEXAxTISxGRAT_TIS_MARK_GRATING_CLS_Y = 18,
} MEXAxTISxGRAT_TIS_MARK_GRATING;



#endif // _MEXAxTISxGRAT_TC_H_
